// <auto-generated />
namespace VerityFinancial.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Stock_Bond_Changes_With_Portfolio_Addition_To_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Stock_Bond_Changes_With_Portfolio_Addition_To_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "201904161401220_Stock_Bond_Changes_With_Portfolio_Addition_To_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
